kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: kafkatopics.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  names:
    plural: kafkatopics
    singular: kafkatopic
    shortNames:
      - kt
    kind: KafkaTopic
    listKind: KafkaTopicList
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - partitions
            - replicas
          properties:
            config:
              type: object
            partitions:
              type: integer
              minimum: 1
            replicas:
              type: integer
              maximum: 32767
              minimum: 1
            topicName:
              type: string
  versions:
    - name: v1alpha1
      served: true
      storage: true
  conversion:
    strategy: None