kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: kafkausers.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  names:
    plural: kafkausers
    singular: kafkauser
    shortNames:
      - ku
    kind: KafkaUser
    listKind: KafkaUserList
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - authentication
          properties:
            authentication:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  enum:
                    - tls
                    - scram-sha-512
            authorization:
              type: object
              required:
                - acls
                - type
              properties:
                acls:
                  type: array
                  items:
                    type: object
                    required:
                      - operation
                      - resource
                    properties:
                      host:
                        type: string
                      operation:
                        type: string
                        enum:
                          - Read
                          - Write
                          - Create
                          - Delete
                          - Alter
                          - Describe
                          - ClusterAction
                          - AlterConfigs
                          - DescribeConfigs
                          - IdempotentWrite
                          - All
                      resource:
                        type: object
                        required:
                          - type
                        properties:
                          name:
                            type: string
                          patternType:
                            type: string
                            enum:
                              - literal
                              - prefix
                          type:
                            type: string
                            enum:
                              - topic
                              - group
                              - cluster
                              - transactionalId
                      type:
                        type: string
                        enum:
                          - allow
                          - deny
                type:
                  type: string
                  enum:
                    - simple
  versions:
    - name: v1alpha1
      served: true
      storage: true
  conversion:
    strategy: None