kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: kafkamirrormakers.kafka.strimzi.io
  labels:
    app: strimzi
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  names:
    plural: kafkamirrormakers
    singular: kafkamirrormaker
    shortNames:
      - kmm
    kind: KafkaMirrorMaker
    listKind: KafkaMirrorMakerList
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - replicas
            - whitelist
            - consumer
            - producer
          properties:
            metrics:
              type: object
            resources:
              type: object
              properties:
                limits:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: '[0-9]+m?$'
                    memory:
                      type: string
                      pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
                requests:
                  type: object
                  properties:
                    cpu:
                      type: string
                      pattern: '[0-9]+m?$'
                    memory:
                      type: string
                      pattern: '[0-9]+([kKmMgGtTpPeE]i?)?$'
            whitelist:
              type: string
            affinity:
              type: object
              properties:
                nodeAffinity:
                  type: object
                  properties:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          preference:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                              matchFields:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                          weight:
                            type: integer
                    requiredDuringSchedulingIgnoredDuringExecution:
                      type: object
                      properties:
                        nodeSelectorTerms:
                          type: array
                          items:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                              matchFields:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                podAffinity:
                  type: object
                  properties:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          podAffinityTerm:
                            type: object
                            properties:
                              labelSelector:
                                type: object
                                properties:
                                  matchExpressions:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        operator:
                                          type: string
                                        values:
                                          type: array
                                          items:
                                            type: string
                                  matchLabels:
                                    type: object
                              namespaces:
                                type: array
                                items:
                                  type: string
                              topologyKey:
                                type: string
                          weight:
                            type: integer
                    requiredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          labelSelector:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                              matchLabels:
                                type: object
                          namespaces:
                            type: array
                            items:
                              type: string
                          topologyKey:
                            type: string
                podAntiAffinity:
                  type: object
                  properties:
                    preferredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          podAffinityTerm:
                            type: object
                            properties:
                              labelSelector:
                                type: object
                                properties:
                                  matchExpressions:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        key:
                                          type: string
                                        operator:
                                          type: string
                                        values:
                                          type: array
                                          items:
                                            type: string
                                  matchLabels:
                                    type: object
                              namespaces:
                                type: array
                                items:
                                  type: string
                              topologyKey:
                                type: string
                          weight:
                            type: integer
                    requiredDuringSchedulingIgnoredDuringExecution:
                      type: array
                      items:
                        type: object
                        properties:
                          labelSelector:
                            type: object
                            properties:
                              matchExpressions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    key:
                                      type: string
                                    operator:
                                      type: string
                                    values:
                                      type: array
                                      items:
                                        type: string
                              matchLabels:
                                type: object
                          namespaces:
                            type: array
                            items:
                              type: string
                          topologyKey:
                            type: string
            producer:
              type: object
              required:
                - bootstrapServers
              properties:
                authentication:
                  type: object
                  required:
                    - type
                  properties:
                    certificateAndKey:
                      type: object
                      required:
                        - certificate
                        - key
                        - secretName
                      properties:
                        certificate:
                          type: string
                        key:
                          type: string
                        secretName:
                          type: string
                    passwordSecret:
                      type: object
                      required:
                        - password
                        - secretName
                      properties:
                        password:
                          type: string
                        secretName:
                          type: string
                    type:
                      type: string
                      enum:
                        - tls
                        - scram-sha-512
                    username:
                      type: string
                bootstrapServers:
                  type: string
                config:
                  type: object
                tls:
                  type: object
                  required:
                    - trustedCertificates
                  properties:
                    trustedCertificates:
                      type: array
                      items:
                        type: object
                        required:
                          - certificate
                          - secretName
                        properties:
                          certificate:
                            type: string
                          secretName:
                            type: string
            consumer:
              type: object
              required:
                - groupId
                - bootstrapServers
              properties:
                authentication:
                  type: object
                  required:
                    - type
                  properties:
                    certificateAndKey:
                      type: object
                      required:
                        - certificate
                        - key
                        - secretName
                      properties:
                        certificate:
                          type: string
                        key:
                          type: string
                        secretName:
                          type: string
                    passwordSecret:
                      type: object
                      required:
                        - password
                        - secretName
                      properties:
                        password:
                          type: string
                        secretName:
                          type: string
                    type:
                      type: string
                      enum:
                        - tls
                        - scram-sha-512
                    username:
                      type: string
                bootstrapServers:
                  type: string
                config:
                  type: object
                groupId:
                  type: string
                numStreams:
                  type: integer
                  minimum: 1
                tls:
                  type: object
                  required:
                    - trustedCertificates
                  properties:
                    trustedCertificates:
                      type: array
                      items:
                        type: object
                        required:
                          - certificate
                          - secretName
                        properties:
                          certificate:
                            type: string
                          secretName:
                            type: string
            version:
              type: string
            template:
              type: object
              properties:
                deployment:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        annotations:
                          type: object
                        labels:
                          type: object
                pod:
                  type: object
                  properties:
                    imagePullSecrets:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                    metadata:
                      type: object
                      properties:
                        annotations:
                          type: object
                        labels:
                          type: object
                    securityContext:
                      type: object
                      properties:
                        fsGroup:
                          type: integer
                        runAsGroup:
                          type: integer
                        runAsNonRoot:
                          type: boolean
                        runAsUser:
                          type: integer
                        seLinuxOptions:
                          type: object
                          properties:
                            level:
                              type: string
                            role:
                              type: string
                            type:
                              type: string
                            user:
                              type: string
                        supplementalGroups:
                          type: array
                          items:
                            type: integer
                        sysctls:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                    terminationGracePeriodSeconds:
                      type: integer
                      minimum: 0
                podDisruptionBudget:
                  type: object
                  properties:
                    maxUnavailable:
                      type: integer
                      minimum: 0
                    metadata:
                      type: object
                      properties:
                        annotations:
                          type: object
                        labels:
                          type: object
            image:
              type: string
            replicas:
              type: integer
              minimum: 1
            tolerations:
              type: array
              items:
                type: object
                properties:
                  effect:
                    type: string
                  key:
                    type: string
                  operator:
                    type: string
                  tolerationSeconds:
                    type: integer
                  value:
                    type: string
            jvmOptions:
              type: object
              properties:
                '-XX':
                  type: object
                '-Xms':
                  type: string
                  pattern: '[0-9]+[mMgG]?'
                '-Xmx':
                  type: string
                  pattern: '[0-9]+[mMgG]?'
                gcLoggingEnabled:
                  type: boolean
            logging:
              type: object
              required:
                - type
              properties:
                loggers:
                  type: object
                name:
                  type: string
                type:
                  type: string
                  enum:
                    - inline
                    - external
  versions:
    - name: v1alpha1
      served: true
      storage: true
  conversion:
    strategy: None