apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: solution-explorer-operator.v0.0.53
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: WebApp
        name: webapps.integreatly.org
        version: v1alpha1
        displayName: SolutionExplorer
        description: SolutionExplorer
  description: Placeholder description
  displayName: Tutorial Web App Operator
  install:
    spec:
      deployments:
        - name: tutorial-web-app-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: tutorial-web-app-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: tutorial-web-app-operator
              spec:
                containers:
                  - command:
                      - tutorial-web-app-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.annotations['olm.targetNamespaces']
                      - name: OPERATOR_NAME
                        value: tutorial-web-app-operator
                    image: quay.io/integreatly/tutorial-web-app-operator:v0.0.53
                    imagePullPolicy: Always
                    name: tutorial-web-app-operator
                    ports:
                      - containerPort: 60000
                        name: metrics
                    resources: {}
                serviceAccountName: tutorial-web-app-operator
      permissions:
        - rules:
            - apiGroups:
                - integreatly.org
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
              verbs:
                - '*'
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - template.openshift.io
              resources:
                - processedtemplates
              verbs:
                - get
                - list
                - create
                - update
                - delete
                - deletecollection
                - watch
            - apiGroups:
                - image.openshift.io
              resources:
                - imagestreams
              verbs:
                - get
                - list
                - create
                - update
                - delete
                - deletecollection
                - watch
            - apiGroups:
                - apps.openshift.io
              resources:
                - deploymentconfigs
              verbs:
                - get
                - list
                - create
                - update
                - delete
                - deletecollection
                - watch
            - apiGroups:
                - route.openshift.io
              resources:
                - routes
                - routes/custom-host
              verbs:
                - get
                - list
                - create
                - update
                - delete
                - deletecollection
                - watch
          serviceAccountName: tutorial-web-app-operator
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.53
  replaces: solution-explorer-operator.v0.0.48