apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: smtpcredentialsets.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: SMTPCredentialSet
    listKind: SMTPCredentialSetList
    plural: smtpcredentialsets
    singular: smtpcredentialset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            secretRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
            tier:
              type: string
            type:
              type: string
          required:
          - type
          - tier
          - secretRef
          type: object
        status:
          properties:
            message:
              type: string
            phase:
              type: string
            provider:
              type: string
            secretRef:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
            strategy:
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
