apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sku-secret
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: addon-managed-api-service-parameters
    stringData:
      addon-managed-api-service: ${QUOTA}
parameters:
  - name: QUOTA
    value: "1"