apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ksm-fuse-online-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: fuseOnline.rules
      rules:
        - alert: FuseOnlineSyndesisServerInstanceDown
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: >-
              Fuse Online Syndesis Server instance {{ "{{" }}$labels.pod{{ "}}" }} in namespace {{ "{{" }}$labels.namespace{{ "}}" }} is down.
          expr: >
            absent(kube_pod_status_ready{namespace="{{ index .Params "Namespace" }}", condition="true", pod=~"syndesis-server-.*"})
          for: 5m
          labels:
            severity: critical
        - alert: FuseOnlineSyndesisUIInstanceDown
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: >-
              Fuse Online Syndesis UI instance {{ "{{" }}$labels.pod{{ "}}" }} in namespace {{ "{{" }}$labels.namespace{{ "}}" }} is down.
          expr: >
            absent(kube_pod_status_ready{namespace="{{ index .Params "Namespace" }}", condition="true", pod=~"syndesis-ui-.*"})
          for: 5m
          labels:
            severity: critical
        - alert: FuseOnlinePodCount
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: Pod count for namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} printf "%.0f" $value {{ "}}" }}. Expected at least 8 pods.
          expr: |
            (1-absent(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"})) or sum(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"}) < 8
          for: 5m
          labels:
            severity: critical