apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ksm-amqonline-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: amqonline.rules
      rules:
        - alert: AMQOnlinePodCount
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: Pod count for namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} printf "%.0f" $value {{ "}}" }}. Expected at least 2 pods.
          expr: |
            (1-absent(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"})) or sum(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"}) < 2
          for: 5m
          labels:
            severity: critical
        - alert: AMQOnlineContainerHighMemory
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: The {{ "{{" }} $labels.container {{ "}}" }} Container in the {{ "{{" }} $labels.pod {{ "}}" }} Pod has been using {{ "{{" }} printf "%.0f" $value {{ "}}" }}% of available memory for longer than 15 minutes.
            scaling_plan: https://github.com/integr8ly/middleware-load-testing/blob/master/sops/amq-scaling.md
          expr: |
            sum by(container, pod) (container_memory_usage_bytes{container!="",namespace="{{ index .Params "Namespace" }}"}) / sum by(container, pod) (kube_pod_container_resource_limits_memory_bytes{namespace="{{ index .Params "Namespace" }}"}) * 100 > 90
          for: 15m
          labels:
            severity: warning
