apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ksm-rhsso-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: rhsso.rules
      rules:
        - alert: RHSSOPodHighMemory
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: The {{ "{{" }} $labels.container {{ "}}" }} pod has been using {{ "{{" }} printf "%.0f" $value {{ "}}" }}% of available memory for longer than 15 minutes.
            scaling_plan: https://github.com/integr8ly/middleware-load-testing/blob/master/sops/sso-scaling.md
          expr: |
            sum by(container) (container_memory_usage_bytes{container!="",namespace="{{ index .Params "Namespace" }}"}) / sum by(container) (kube_pod_container_resource_limits_memory_bytes{namespace="{{ index .Params "Namespace" }}"}) * 100 > 90
          for: 15m
          labels:
            severity: warning
