apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: {{ index .Params "MonitoringKey" }}
  name: ksm-solution-explorer-alerts
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
    - name: solution-explorer.rules
      rules:
        - alert: SolutionExplorerPodCount
          annotations:
            sop_url: https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md
            message: Pod count for namespace {{ "{{" }} $labels.namespace {{ "}}" }} is {{ "{{" }} printf "%.0f" $value {{ "}}" }}. Expected exactly 2 pods.
          expr: |
            (1-absent(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"})) or sum(kube_pod_status_ready{condition="true", namespace="{{ index .Params "Namespace" }}"}) != 2
          for: 5m
          labels:
            severity: critical