package resources

// Add alert strings here
const (
	sopUrlRhoamBase                                            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/"
	sopUrlPostgresInstanceUnavailable                          = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresConnectionFailed                             = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisCacheUnavailable                                = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisConnectionFailed                                = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresResourceStatusPhasePending                   = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresResourceStatusPhaseFailed                    = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisResourceStatusPhasePending                      = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisResourceStatusPhaseFailed                       = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresWillFill                                     = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresFreeableMemoryLow                            = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisMemoryUsageHigh                                 = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlPostgresCpuUsageHigh                                 = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisCpuUsageHigh                                    = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlRedisServiceMaintenanceCritical                      = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	SopUrlEndpointAvailableAlert                               = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	SopUrlAlertsAndTroubleshooting                             = "https://github.com/RHCloudServices/integreatly-help/boop.md"
	sopUrlCloudResourceDeletionStatusFailed                    = "https://github.com/RHCloudServices/integreatly-help/tree/master/sops/2.x/alerts/clean_up_cloud_resources_failed_teardown.asciidoc"
	sopUrlSendGridSmtpSecretExists                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/alerts/sendgrid_smtp_secret_not_present.asciidoc"
	SopUrlDeadMansSnitchSecretExists                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/DeadMansSnitchSecretNotPresent.asciidoc"
	SopUrlMarin3rEnvoyApicastProductionContainerDown           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/Marin3rEnvoyApicastProductionContainerDown.asciidoc"
	SopUrlMarin3rEnvoyApicastStagingContainerDown              = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/Marin3rEnvoyApicastStagingContainerDown.asciidoc"
	SopUrlOperatorInstallDelayed                               = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/OperatorInstallDelayed.asciidoc"
	SopUrlUpgradeExpectedDurationExceeded                      = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/UpgradeExpectedDurationExceeded.asciidoc"
	SopUrlRHOAMIsInReconcilingErrorState                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMIsInReconcilingErrorState.asciidoc"
	SopUrlRHOAMCloudResourceOperatorMetricsServiceEndpointDown = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMCloudResourceOperatorMetricsServiceEndpointDown.asciidoc"
	SopUrlRHOAMCloudResourceOperatorVPCActionFailed            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMCloudResourceOperatorVPCActionFailed.asciidoc"
	SopUrlRHOAMThreeScaleApicastProductionServiceEndpointDown  = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleApicastProductionServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleApicastStagingServiceEndpointDown     = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleApicastStagingServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleBackendListenerServiceEndpointDown    = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleBackendListenerServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleZyncServiceEndpointDown               = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleZyncServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleZyncDatabaseServiceEndpointDown       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleZyncDatabaseServiceEndpointDown.asciidoc"
	SopUrlThreeScaleBackendWorkerPod                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleBackendWorkerPod.asciidoc"
	SopUrlThreeScaleAdminUIBBT                                 = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleAdminUIBBT.asciidoc"
	SopUrlThreeScaleDeveloperUIBBT                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleDeveloperUIBBT.asciidoc"
	SopUrlThreeScaleSystemAdminUIBBT                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleSystemAdminUIBBT.asciidoc"
	SopUrlPodDistributionIncorrect                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/multi-az/pod_distribution.md"
	SopUrlSloRhssoAvailabilityAlert                            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/SloRhssoAvailabilityAlert.asciidoc"
	SopUrlSloUserSsoAvailabilityAlert                          = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/SloUserSsoAvailabilityAlert.asciidoc"
	SopUrlTestFireAlerts                                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/2.x/cssre_info/info_test_fire_alerts.md#resolve-test-alerts"
)
