package resources

// Add alert strings here
const (
	sopUrlAddonManagedApiServiceParametersExists               = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/AddonManagedApiServiceParameters.asciidoc"
	sopUrlRhoamBase                                            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/"
	sopUrlPostgresInstanceUnavailable                          = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_instance_unavailable.asciidoc"
	sopUrlPostgresConnectionFailed                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_connection_failed.asciidoc"
	sopUrlRedisCacheUnavailable                                = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_cache_unavailable.asciidoc"
	sopUrlRedisConnectionFailed                                = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_connection_failed.asciidoc"
	sopUrlPostgresResourceStatusPhasePending                   = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_resource_status_phase_pending.asciidoc"
	sopUrlPostgresResourceStatusPhaseFailed                    = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_resource_status_phase_failed.asciidoc"
	sopUrlRedisResourceStatusPhasePending                      = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_resource_status_phase_pending.asciidoc"
	sopUrlRedisResourceStatusPhaseFailed                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_resource_status_phase_failed.asciidoc"
	sopUrlPostgresWillFill                                     = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_storage_alerts.asciidoc"
	sopUrlPostgresFreeableMemoryLow                            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_freeable_memory_low.asciidoc"
	sopUrlRedisMemoryUsageHigh                                 = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_memory_usage_high.asciidoc"
	sopUrlPostgresCpuUsageHigh                                 = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/postgres_cpu_usage_high.asciidoc"
	sopUrlRedisCpuUsageHigh                                    = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/redis_cpu_usage_high.asciidoc"
	sopUrlRedisServiceMaintenanceCritical                      = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RedisServiceMaintenanceCritical.asciidoc"
	SopUrlEndpointAvailableAlert                               = "https://github.com/RHCloudServices/integreatly-help/tree/master/sops/rhoam/alerts/service_endpoint_down.asciidoc"
	SopUrlAlertsAndTroubleshooting                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/alerts_and_troubleshooting.md"
	sopUrlCloudResourceDeletionStatusFailed                    = "https://github.com/RHCloudServices/integreatly-help/tree/master/sops/rhoam/alerts/clean_up_cloud_resources_failed_teardown.asciidoc" //#nosec G101 -- This is a false positive
	sopUrlSendGridSmtpSecretExists                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/sendgrid_smtp_secret_not_present.asciidoc"         //#nosec G101 -- This is a false positive
	SopUrlDeadMansSnitchSecretExists                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/DeadMansSnitchSecretNotPresent.asciidoc"           //#nosec G101 -- This is a false positive
	SopUrlMarin3rEnvoyApicastProductionContainerDown           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/Marin3rEnvoyApicastProductionContainerDown.asciidoc"
	SopUrlMarin3rEnvoyApicastStagingContainerDown              = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/Marin3rEnvoyApicastStagingContainerDown.asciidoc"
	SopUrlOperatorInstallDelayed                               = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/OperatorInstallDelayed.asciidoc"
	SopUrlUpgradeExpectedDurationExceeded                      = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/UpgradeExpectedDurationExceeded.asciidoc"
	SopUrlRHOAMIsInReconcilingErrorState                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMIsInReconcilingErrorState.asciidoc"
	SopUrlRHOAMCloudResourceOperatorMetricsServiceEndpointDown = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMCloudResourceOperatorMetricsServiceEndpointDown.asciidoc"
	SopUrlRHOAMCloudResourceOperatorVPCActionFailed            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMCloudResourceOperatorVPCActionFailed.asciidoc"
	SopUrlRHOAMThreeScaleApicastProductionServiceEndpointDown  = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleApicastProductionServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleApicastStagingServiceEndpointDown     = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleApicastStagingServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleBackendListenerServiceEndpointDown    = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleBackendListenerServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleZyncServiceEndpointDown               = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleZyncServiceEndpointDown.asciidoc"
	SopUrlRHOAMThreeScaleZyncDatabaseServiceEndpointDown       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/RHOAMThreeScaleZyncDatabaseServiceEndpointDown.asciidoc"
	SopUrlThreeScaleBackendWorkerPod                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleBackendWorkerPod.asciidoc"
	SopUrlThreeScaleAdminUIBBT                                 = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleAdminUIBBT.asciidoc"
	SopUrlThreeScaleDeveloperUIBBT                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleDeveloperUIBBT.asciidoc"
	SopUrlThreeScaleSystemAdminUIBBT                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/ThreeScaleSystemAdminUIBBT.asciidoc"
	SopUrlPodDistributionIncorrect                             = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/multi-az/pod_distribution.md"
	SopUrlSloRhssoAvailabilityAlert                            = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/SloRhssoAvailabilityAlert.asciidoc"
	SopUrlSloUserSsoAvailabilityAlert                          = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/SloUserSsoAvailabilityAlert.asciidoc"
	SopUrlTestFireAlerts                                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/cssre_info/info_test_fire_alerts.md#resolve-test-alerts"
	SopUrlRHOAMServiceDefinition                               = "https://access.redhat.com/articles/5534341"
	SopUrlDnsBypassThreeScaleAdminUI                           = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/DnsBypassThreeScaleAdminUI.asciidoc"
	SopUrlDnsBypassThreeScaleDeveloperUI                       = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/DnsBypassThreeScaleDeveloperUI.asciidoc"
	SopUrlDnsBypassThreeScaleSystemAdminUI                     = "https://github.com/RHCloudServices/integreatly-help/blob/master/sops/rhoam/alerts/DnsBypassThreeScaleSystemAdminUI.asciidoc"
)
