// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package marketplace

import (
	"context"
	"github.com/operator-framework/operator-lifecycle-manager/pkg/api/apis/operators/v1alpha1"
	"github.com/operator-framework/operator-lifecycle-manager/pkg/lib/ownerutil"
	"github.com/operator-framework/operator-marketplace/pkg/apis/operators/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

var (
	lockMarketplaceInterfaceMockCreateSubscription         sync.RWMutex
	lockMarketplaceInterfaceMockGetSubscriptionInstallPlan sync.RWMutex
)

// Ensure, that MarketplaceInterfaceMock does implement MarketplaceInterface.
// If this is not the case, regenerate this file with moq.
var _ MarketplaceInterface = &MarketplaceInterfaceMock{}

// MarketplaceInterfaceMock is a mock implementation of MarketplaceInterface.
//
//     func TestSomethingThatUsesMarketplaceInterface(t *testing.T) {
//
//         // make and configure a mocked MarketplaceInterface
//         mockedMarketplaceInterface := &MarketplaceInterfaceMock{
//             CreateSubscriptionFunc: func(ctx context.Context, serverClient client.Client, owner ownerutil.Owner, os v1.OperatorSource, ns string, pkg string, channel string, operatorGroupNamespaces []string, approvalStrategy v1alpha1.Approval) error {
// 	               panic("mock out the CreateSubscription method")
//             },
//             GetSubscriptionInstallPlanFunc: func(ctx context.Context, serverClient client.Client, subName string, ns string) (*v1alpha1.InstallPlan, *v1alpha1.Subscription, error) {
// 	               panic("mock out the GetSubscriptionInstallPlan method")
//             },
//         }
//
//         // use mockedMarketplaceInterface in code that requires MarketplaceInterface
//         // and then make assertions.
//
//     }
type MarketplaceInterfaceMock struct {
	// CreateSubscriptionFunc mocks the CreateSubscription method.
	CreateSubscriptionFunc func(ctx context.Context, serverClient client.Client, owner ownerutil.Owner, os v1.OperatorSource, ns string, pkg string, channel string, operatorGroupNamespaces []string, approvalStrategy v1alpha1.Approval) error

	// GetSubscriptionInstallPlanFunc mocks the GetSubscriptionInstallPlan method.
	GetSubscriptionInstallPlanFunc func(ctx context.Context, serverClient client.Client, subName string, ns string) (*v1alpha1.InstallPlan, *v1alpha1.Subscription, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSubscription holds details about calls to the CreateSubscription method.
		CreateSubscription []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ServerClient is the serverClient argument value.
			ServerClient client.Client
			// Owner is the owner argument value.
			Owner ownerutil.Owner
			// Os is the os argument value.
			Os v1.OperatorSource
			// Ns is the ns argument value.
			Ns string
			// Pkg is the pkg argument value.
			Pkg string
			// Channel is the channel argument value.
			Channel string
			// OperatorGroupNamespaces is the operatorGroupNamespaces argument value.
			OperatorGroupNamespaces []string
			// ApprovalStrategy is the approvalStrategy argument value.
			ApprovalStrategy v1alpha1.Approval
		}
		// GetSubscriptionInstallPlan holds details about calls to the GetSubscriptionInstallPlan method.
		GetSubscriptionInstallPlan []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ServerClient is the serverClient argument value.
			ServerClient client.Client
			// SubName is the subName argument value.
			SubName string
			// Ns is the ns argument value.
			Ns string
		}
	}
}

// CreateSubscription calls CreateSubscriptionFunc.
func (mock *MarketplaceInterfaceMock) CreateSubscription(ctx context.Context, serverClient client.Client, owner ownerutil.Owner, os v1.OperatorSource, ns string, pkg string, channel string, operatorGroupNamespaces []string, approvalStrategy v1alpha1.Approval) error {
	if mock.CreateSubscriptionFunc == nil {
		panic("MarketplaceInterfaceMock.CreateSubscriptionFunc: method is nil but MarketplaceInterface.CreateSubscription was just called")
	}
	callInfo := struct {
		Ctx                     context.Context
		ServerClient            client.Client
		Owner                   ownerutil.Owner
		Os                      v1.OperatorSource
		Ns                      string
		Pkg                     string
		Channel                 string
		OperatorGroupNamespaces []string
		ApprovalStrategy        v1alpha1.Approval
	}{
		Ctx:                     ctx,
		ServerClient:            serverClient,
		Owner:                   owner,
		Os:                      os,
		Ns:                      ns,
		Pkg:                     pkg,
		Channel:                 channel,
		OperatorGroupNamespaces: operatorGroupNamespaces,
		ApprovalStrategy:        approvalStrategy,
	}
	lockMarketplaceInterfaceMockCreateSubscription.Lock()
	mock.calls.CreateSubscription = append(mock.calls.CreateSubscription, callInfo)
	lockMarketplaceInterfaceMockCreateSubscription.Unlock()
	return mock.CreateSubscriptionFunc(ctx, serverClient, owner, os, ns, pkg, channel, operatorGroupNamespaces, approvalStrategy)
}

// CreateSubscriptionCalls gets all the calls that were made to CreateSubscription.
// Check the length with:
//     len(mockedMarketplaceInterface.CreateSubscriptionCalls())
func (mock *MarketplaceInterfaceMock) CreateSubscriptionCalls() []struct {
	Ctx                     context.Context
	ServerClient            client.Client
	Owner                   ownerutil.Owner
	Os                      v1.OperatorSource
	Ns                      string
	Pkg                     string
	Channel                 string
	OperatorGroupNamespaces []string
	ApprovalStrategy        v1alpha1.Approval
} {
	var calls []struct {
		Ctx                     context.Context
		ServerClient            client.Client
		Owner                   ownerutil.Owner
		Os                      v1.OperatorSource
		Ns                      string
		Pkg                     string
		Channel                 string
		OperatorGroupNamespaces []string
		ApprovalStrategy        v1alpha1.Approval
	}
	lockMarketplaceInterfaceMockCreateSubscription.RLock()
	calls = mock.calls.CreateSubscription
	lockMarketplaceInterfaceMockCreateSubscription.RUnlock()
	return calls
}

// GetSubscriptionInstallPlan calls GetSubscriptionInstallPlanFunc.
func (mock *MarketplaceInterfaceMock) GetSubscriptionInstallPlan(ctx context.Context, serverClient client.Client, subName string, ns string) (*v1alpha1.InstallPlan, *v1alpha1.Subscription, error) {
	if mock.GetSubscriptionInstallPlanFunc == nil {
		panic("MarketplaceInterfaceMock.GetSubscriptionInstallPlanFunc: method is nil but MarketplaceInterface.GetSubscriptionInstallPlan was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		ServerClient client.Client
		SubName      string
		Ns           string
	}{
		Ctx:          ctx,
		ServerClient: serverClient,
		SubName:      subName,
		Ns:           ns,
	}
	lockMarketplaceInterfaceMockGetSubscriptionInstallPlan.Lock()
	mock.calls.GetSubscriptionInstallPlan = append(mock.calls.GetSubscriptionInstallPlan, callInfo)
	lockMarketplaceInterfaceMockGetSubscriptionInstallPlan.Unlock()
	return mock.GetSubscriptionInstallPlanFunc(ctx, serverClient, subName, ns)
}

// GetSubscriptionInstallPlanCalls gets all the calls that were made to GetSubscriptionInstallPlan.
// Check the length with:
//     len(mockedMarketplaceInterface.GetSubscriptionInstallPlanCalls())
func (mock *MarketplaceInterfaceMock) GetSubscriptionInstallPlanCalls() []struct {
	Ctx          context.Context
	ServerClient client.Client
	SubName      string
	Ns           string
} {
	var calls []struct {
		Ctx          context.Context
		ServerClient client.Client
		SubName      string
		Ns           string
	}
	lockMarketplaceInterfaceMockGetSubscriptionInstallPlan.RLock()
	calls = mock.calls.GetSubscriptionInstallPlan
	lockMarketplaceInterfaceMockGetSubscriptionInstallPlan.RUnlock()
	return calls
}
