// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package products

import (
	"context"
	"github.com/integr8ly/integreatly-operator/pkg/apis/integreatly/v1alpha1"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

var (
	lockInterfaceMockReconcile sync.RWMutex
)

// Ensure, that InterfaceMock does implement Interface.
// If this is not the case, regenerate this file with moq.
var _ Interface = &InterfaceMock{}

// InterfaceMock is a mock implementation of Interface.
//
//     func TestSomethingThatUsesInterface(t *testing.T) {
//
//         // make and configure a mocked Interface
//         mockedInterface := &InterfaceMock{
//             ReconcileFunc: func(ctx context.Context, inst *v1alpha1.Installation, product *v1alpha1.InstallationProductStatus, serverClient client.Client) (v1alpha1.StatusPhase, error) {
// 	               panic("mock out the Reconcile method")
//             },
//         }
//
//         // use mockedInterface in code that requires Interface
//         // and then make assertions.
//
//     }
type InterfaceMock struct {
	// ReconcileFunc mocks the Reconcile method.
	ReconcileFunc func(ctx context.Context, inst *v1alpha1.Installation, product *v1alpha1.InstallationProductStatus, serverClient client.Client) (v1alpha1.StatusPhase, error)

	// calls tracks calls to the methods.
	calls struct {
		// Reconcile holds details about calls to the Reconcile method.
		Reconcile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Inst is the inst argument value.
			Inst *v1alpha1.Installation
			// Product is the product argument value.
			Product *v1alpha1.InstallationProductStatus
			// ServerClient is the serverClient argument value.
			ServerClient client.Client
		}
	}
}

// Reconcile calls ReconcileFunc.
func (mock *InterfaceMock) Reconcile(ctx context.Context, inst *v1alpha1.Installation, product *v1alpha1.InstallationProductStatus, serverClient client.Client) (v1alpha1.StatusPhase, error) {
	if mock.ReconcileFunc == nil {
		panic("InterfaceMock.ReconcileFunc: method is nil but Interface.Reconcile was just called")
	}
	callInfo := struct {
		Ctx          context.Context
		Inst         *v1alpha1.Installation
		Product      *v1alpha1.InstallationProductStatus
		ServerClient client.Client
	}{
		Ctx:          ctx,
		Inst:         inst,
		Product:      product,
		ServerClient: serverClient,
	}
	lockInterfaceMockReconcile.Lock()
	mock.calls.Reconcile = append(mock.calls.Reconcile, callInfo)
	lockInterfaceMockReconcile.Unlock()
	return mock.ReconcileFunc(ctx, inst, product, serverClient)
}

// ReconcileCalls gets all the calls that were made to Reconcile.
// Check the length with:
//     len(mockedInterface.ReconcileCalls())
func (mock *InterfaceMock) ReconcileCalls() []struct {
	Ctx          context.Context
	Inst         *v1alpha1.Installation
	Product      *v1alpha1.InstallationProductStatus
	ServerClient client.Client
} {
	var calls []struct {
		Ctx          context.Context
		Inst         *v1alpha1.Installation
		Product      *v1alpha1.InstallationProductStatus
		ServerClient client.Client
	}
	lockInterfaceMockReconcile.RLock()
	calls = mock.calls.Reconcile
	lockInterfaceMockReconcile.RUnlock()
	return calls
}
