package addon

import (
	"strings"

	integreatlyv1alpha1 "github.com/integr8ly/integreatly-operator/api/v1alpha1"
)

var quotaConfig = `
[
    {
        "name":"100 Million",
        "param":"1000",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":69445,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":7,
                "resources":{
                    "requests":{
                        "cpu":0.5,
                        "memory":"600Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"700Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":5,
                "resources":{
                    "requests":{
                        "cpu":0.4,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.6,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":8,
                "resources":{
                    "requests":{
                        "cpu":0.6,
                        "memory":"275Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":1,
                        "memory":"2000Mi"
                    },
                    "limits":{
                        "cpu":2,
                        "memory":"2000Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.15,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"50 Million",
        "param":"500",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":34723,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":5,
                "resources":{
                    "requests":{
                        "cpu":0.5,
                        "memory":"600Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"700Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":4,
                "resources":{
                    "requests":{
                        "cpu":0.4,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.6,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.6,
                        "memory":"275Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":1,
                        "memory":"2000Mi"
                    },
                    "limits":{
                        "cpu":2,
                        "memory":"2000Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.15,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"20 Million",
        "param":"200",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":13889,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.25,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.6,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.15,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.3,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.6,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.10,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.20,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"10 Million",
        "param":"100",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":6945,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.15,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.5,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.1,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.25,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.2,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.5,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.05,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.15,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"5 Million",
        "param":"50",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":3473,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.1,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.05,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.15,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.1,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":3,
                "resources":{
                    "requests":{
                        "cpu":0.05,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.15,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"1 Million",
        "param":"10",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":695,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.03,
                        "memory":"60Mi"
                    },
                    "limits":{
                        "cpu":0.09,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.02,
                        "memory":"40Mi"
                    },
                    "limits":{
                        "cpu":0.06,
                        "memory":"80Mi"
                    }
                }
            }
        }
    },
    {
        "name":"100K - Evaluation",
        "param":"0",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":70,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.03,
                        "memory":"60Mi"
                    },
                    "limits":{
                        "cpu":0.09,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.02,
                        "memory":"40Mi"
                    },
                    "limits":{
                        "cpu":0.06,
                        "memory":"80Mi"
                    }
                }
            }
        }
    },
    {
        "name":"100K",
        "param":"1",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":70,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"450Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"500Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.03,
                        "memory":"60Mi"
                    },
                    "limits":{
                        "cpu":0.09,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"300Mi"
                    }
                }
            },
            "rhssouser":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.75,
                        "memory":"1500Mi"
                    },
                    "limits":{
                        "cpu":1.5,
                        "memory":"1500Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.02,
                        "memory":"40Mi"
                    },
                    "limits":{
                        "cpu":0.06,
                        "memory":"80Mi"
                    }
                }
            }
        }
    }
]
`

var mtQuotaConfig = `
[
    {
        "name":"1 Million",
        "param":"10",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":695,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":5,
                "resources":{
                    "requests":{
                        "cpu":0.5,
                        "memory":"700Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"1400Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":4,
                "resources":{
                    "requests":{
                        "cpu":0.4,
                        "memory":"100Mi"
                    },
                    "limits":{
                        "cpu":0.6,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.6,
                        "memory":"275Mi"
                    },
                    "limits":{
                        "cpu":1,
                        "memory":"300Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.15,
                        "memory":"50Mi"
                    },
                    "limits":{
                        "cpu":0.3,
                        "memory":"100Mi"
                    }
                }
            }
        }
    },
    {
        "name":"100K",
        "param":"1",
        "rate-limiting":{
            "unit":"minute",
            "requests_per_unit":70,
            "alert_limits":[
                
            ]
        },
        "resources":{
            "backend_listener":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"455Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"505Mi"
                    }
                }
            },
            "backend_worker":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.03,
                        "memory":"60Mi"
                    },
                    "limits":{
                        "cpu":0.09,
                        "memory":"100Mi"
                    }
                }
            },
            "apicast_production":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.06,
                        "memory":"250Mi"
                    },
                    "limits":{
                        "cpu":0.18,
                        "memory":"300Mi"
                    }
                }
            },
            "ratelimit":{
                "replicas":2,
                "resources":{
                    "requests":{
                        "cpu":0.02,
                        "memory":"40Mi"
                    },
                    "limits":{
                        "cpu":0.06,
                        "memory":"80Mi"
                    }
                }
            }
        }
    }
]
`

func GetQuotaConfig(installType string) string {
	if integreatlyv1alpha1.IsRHOAMMultitenant(integreatlyv1alpha1.InstallationType(installType)) {
		return strings.TrimSpace(mtQuotaConfig)
	}
	return strings.TrimSpace(quotaConfig)
}
