apiVersion: v1
kind: Service
metadata:
  labels:
    name: rhmi-operator
  name: operator-metrics-service
  namespace: system
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
  selector:
    name: rhmi-operator
