apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: rhmi-operator
  name: rhmi-operator-metrics
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  selector:
    matchLabels:
      name: rhmi-operator
