apiVersion: v1
kind: Service
metadata:
  name: syndesis-integrations
  namespace: {{ index .Params "Namespace" }}
  labels:
    app: syndesis
    syndesis.io/app: syndesis
    syndesis.io/component: integration
    syndesis.io/type: infrastructure
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9779
  selector:
    syndesis.io/app: syndesis
    syndesis.io/component: integration
