apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorSource
    metadata:
      name: ${OPERATOR_SOURCE_NAME}
      namespace: openshift-marketplace
    spec:
      authorizationToken: {}
      displayName: Integreatly Operators
      endpoint: 'https://quay.io/cnr'
      publisher: Integreatly Publisher
      registryNamespace: ${OPERATOR_SOURCE_REGISTRY_NAMESPACE}
      type: appregistry
  - apiVersion: operators.coreos.com/v1
    kind: CatalogSourceConfig
    metadata:
      name: ${CATALOG_SOURCE_CONFIG_NAME}
      namespace: openshift-marketplace
    spec:
      csDisplayName: ${CATALOG_SOURCE_CONFIG_NAME}
      csPublisher: Red Hat
      packages: integreatly
      targetNamespace: ${NAMESPACE}
      source: ${OPERATOR_SOURCE_NAME}
parameters:
  - description: The namespace to deploy into
    displayName: Namespace
    name: NAMESPACE
    value: integreatly
  - description: The name of the operator source
    displayName: Operator Source Name
    name: OPERATOR_SOURCE_NAME
    value: integreatly-operators
  - description: The name of the operator source registry namespace
    displayName: Operator Source Registry Namespace
    name: OPERATOR_SOURCE_REGISTRY_NAMESPACE
    value: integreatly
  - description: The name of the catalog source config
    displayName: Catalog Source Config Name
    name: CATALOG_SOURCE_CONFIG_NAME
    value: installed-integreatly-operator
