#!/bin/bash -e
#
# Test the Dockerfile.tools image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#
WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z "${IMAGE_NAME}" ]; then
   IMAGE_NAME=registry.svc.ci.openshift.org/integr8ly/intly-operator-base-image:latest
fi

docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'operator-sdk version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'go version'

docker run --rm -u $UID -v "${WORK_DIR}/../..:/integreatly-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /integreatly-operator && make vendor/check"
docker run --rm -u $UID -v "${WORK_DIR}/../..:/integreatly-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /integreatly-operator && make code/check"
docker run --rm -u $UID -v "${WORK_DIR}/../..:/integreatly-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /integreatly-operator && make code/compile"
docker run --rm -u $UID -v "${WORK_DIR}/../..:/integreatly-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /integreatly-operator && make test/unit"

#Requires you to be oc logged in to any cluster on your host machine
CLEANUP_RESOURCES=true
INTEGREATLY_OPERATOR_IMAGE="registry.svc.ci.openshift.org/integr8ly/integreatly-operator:integreatly-operator"
E2E_CMD="CLEANUP_RESOURCES=${CLEANUP_RESOURCES} operator-sdk --verbose test local ./openshift-ci/test/e2e --namespace=integreatly --go-test-flags \"-timeout=60m\" --debug --image=${INTEGREATLY_OPERATOR_IMAGE}"
docker run --rm -e KUBECONFIG=/kube.config -v "${HOME}/.kube/config":/kube.config:z -u $UID -v "${WORK_DIR}/../..:/integreatly-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /integreatly-operator && ${E2E_CMD}"

echo "SUCCESS!"
