apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mobiledeveloperconsoles.mdc.aerogear.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: mdc.aerogear.org
  names:
    kind: MobileDeveloperConsole
    listKind: MobileDeveloperConsoleList
    plural: mobiledeveloperconsoles
    shortNames:
    - mdc
    singular: mobiledeveloperconsole
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            oAuthClientId:
              description: OAuthClientId is the id of the OAuthClient to use when
                protecting the Mobile Developer Console instance with OpenShift OAuth
                Proxy.
              type: string
            oAuthClientSecret:
              description: OAuthClientSecret is the secret of the OAuthClient to use
                when protecting the Mobile Developer Console instance with OpenShift
                OAuth Proxy.
              type: string
          required:
          - oAuthClientId
          - oAuthClientSecret
          type: object
        status:
          properties:
            phase:
              type: string
          required:
          - phase
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
