# This file represents informations around components used within RHOAM and RHMI
# name - the name of the components
# version - version of the components - by github tag
# url - url to github repo of the component
# installType - installation type where the component is required
# manifestDir - name of the directory where manifest is stored
# quayScan - decide whether the image should be scanned or not 
products:
  - name: 3scale-operator
    version: 3scale-2.11.0-GA
    url: "https://github.com/3scale/3scale-operator"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-3scale"
    quayScan: true
  - name: apicurito-registry-operator
    version: 0.0.3
    url: "https://github.com/Apicurio/apicurio-registry-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-apicurito"
    quayScan: false
  - name: cloud-resource-operator
    version: v0.36.0
    url: "https://github.com/integr8ly/cloud-resource-operator"
    installType: "rhoam/rhmi"
    manifestsDir: "integreatly-cloud-resources"
    quayScan: true
  - name: grafana-operator
    version: v3.10.4
    url: "https://github.com/integr8ly/grafana-operator"
    installType: "rhoam/rhmi"
    manifestsDir: "integreatly-grafana"
    quayScan: true
  - name: marin3r
    version: v0.8.0
    url: "https://github.com/3scale-ops/marin3r"
    installType: "rhoam"
    manifestsDir: "integreatly-marin3r"
    quayScan: true
  - name: application-monitoring-operator
    version: v1.8.0
    url: "https://github.com/integr8ly/application-monitoring-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-monitoring"
    quayScan: true
  - name: keycloak-operator
    version: 15.0.2
    url: "https://github.com/keycloak/keycloak-operator"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-rhsso"
    quayScan: true
  - name: keycloak-client
    version: v0.1.7
    url: "https://github.com/integr8ly/keycloak-client"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-keycloak-client"
    quayScan: false
  - name: tutorial-web-app-operator
    version: v0.0.62
    url: "https://github.com/integr8ly/tutorial-web-app-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-solution-explorer"
    quayScan: false
  - name: unifiedpush-operator
    version: v0.5.0
    url: "https://github.com/aerogear/unifiedpush-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-unifiedpush"
    quayScan: false
  - name: observability-operator
    version: v3.0.8
    url: "https://github.com/redhat-developer/observability-operator"
    installType: "rhoam"
    manifestsDir: "integreatly-observability-operator"
    quayScan: true
