# This file represents informations around components used within RHOAM and RHMI
# name - the name of the components
# version - version of the components - by github tag
# url - url to github repo of the component
# installType - installation type where the component is required
# manifestDir - name of the directory where manifest is stored
# quayScan - decide whether the image should be scanned or not 
products:
  - name: 3scale-operator
    version: 3scale-2.13.1-GA
    url: "https://github.com/3scale/3scale-operator"
    installType: "rhoam"
    manifestsDir: "integreatly-3scale"
    quayScan: true
  - name: cloud-resource-operator
    version: v1.1.5
    url: "https://github.com/integr8ly/cloud-resource-operator"
    installType: "rhoam"
    manifestsDir: "integreatly-cloud-resources"
    quayScan: true
  - name: marin3r
    version: v0.13.3
    url: "https://github.com/3scale-sre/marin3r"
    installType: "rhoam"
    manifestsDir: "integreatly-marin3r"
    quayScan: true
  - name: rhsso-operator
    version: 18.0.x
    url: "git@gitlab.cee.redhat.com:keycloak/keycloak-operator-prod.git"
    installType: "rhoam"
    manifestsDir: "integreatly-rhsso"
    quayScan: true
  - name: keycloak-client
    version: v0.1.8
    url: "https://github.com/integr8ly/keycloak-client"
    installType: "rhoam"
    manifestsDir: "integreatly-keycloak-client"
    quayScan: false
