products:
  - name: 3scale-operator
    version: 3scale-2.10.0-GA
    url: "https://github.com/3scale/3scale-operator"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-3scale"
    relatedImages: false
  - name: apicurito-registry-operator
    version: 0.0.3
    url: "https://github.com/Apicurio/apicurio-registry-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-apicurito"
    relatedImages: false
  - name: cloud-resource-operator
    version: v0.24.0
    url: "https://github.com/integr8ly/cloud-resource-operator"
    installType: "rhoam/rhmi"
    manifestsDir: "integreatly-cloud-resources"
    relatedImages: true
  - name: grafana-operator
    version: v3.10.1
    url: "https://github.com/integr8ly/grafana-operator"
    installType: "rhoam/rhmi"
    manifestsDir: "integreatly-grafana"
    relatedImages: true
  - name: marin3r
    version: v0.7.0
    url: "https://github.com/3scale/marin3r"
    installType: "rhoam"
    manifestsDir: "integreatly-marin3r"
    relatedImages: true
  - name: application-monitoring-operator
    version: v1.6.0
    url: "https://github.com/integr8ly/application-monitoring-operator"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-monitoring"
    relatedImages: true
  - name: keycloak-operator
    version: 13.0.1
    url: "https://github.com/keycloak/keycloak-operator"
    installType: "rhmi/rhoam"
    manifestsDir: "integreatly-rhsso"
    relatedImages: true
  - name: tutorial-web-app-operator
    version: v0.0.62
    url: "https://github.com/integr8ly/tutorial-web-app-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-solution-explorer"
    relatedImages: false
  - name: unifiedpush-operator
    version: v0.5.0
    url: "https://github.com/aerogear/unifiedpush-operator"
    installType: "rhmi"
    manifestsDir: "integreatly-uninfedpush"
    relatedImages: false