apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
  - apiVersion: keycloak.org/v1alpha1
    kind: KeycloakRealm
    metadata:
      name: ${REALM}
      namespace: ${NAMESPACE}
      labels:
        sso: ${REALM}
    spec:
      instanceSelector:
        matchLabels:
          sso: integreatly
      realm:
        displayName: ${REALM_DISPLAY_NAME}
        enabled: true
        id: ${REALM}
        realm: ${REALM}

  - apiVersion: keycloak.org/v1alpha1
    kind: KeycloakClient
    metadata:
      name: ${REALM}-client
      namespace: ${NAMESPACE}
    spec:
      realmSelector:
        matchLabels:
          sso: ${REALM}
      client:
        id: openshift
        clientId: openshift
        rootUrl: ${OAUTH_URL}
        secret: ${CLIENT_SECRET}
        redirectUris:
          - ${OAUTH_URL}/oauth2callback/${REALM}
        directAccessGrantsEnabled: true
        enabled: true
        clientAuthenticatorType: client-secret
        fullScopeAllowed: true
        access:
          configure: true
          manage: true
          view: true
        standardFlowEnabled: true
        webOrigins:
          - ${OAUTH_URL}
          - ${OAUTH_URL}/*
        protocolMappers:
          - config:
              access.token.claim: 'true'
              claim.name: given_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: firstName
              userinfo.token.claim: 'true'
            consentRequired: true
            consentText: '${givenName}'
            name: given name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              id.token.claim: 'true'
              userinfo.token.claim: 'true'
            consentRequired: true
            consentText: '${fullName}'
            name: full name
            protocol: openid-connect
            protocolMapper: oidc-full-name-mapper
          - config:
              access.token.claim: 'true'
              claim.name: family_name
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: lastName
              userinfo.token.claim: 'true'
            consentRequired: true
            consentText: '${familyName}'
            name: family name
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              attribute.name: Role
              attribute.nameformat: Basic
              single: 'false'
            consentText: '${familyName}'
            name: role list
            protocol: saml
            protocolMapper: saml-role-list-mapper
          - config:
              access.token.claim: 'true'
              claim.name: email
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: email
              userinfo.token.claim: 'true'
            consentRequired: true
            consentText: '${email}'
            name: email
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper
          - config:
              access.token.claim: 'true'
              claim.name: preferred_username
              id.token.claim: 'true'
              jsonType.label: String
              user.attribute: username
              userinfo.token.claim: 'true'
            consentText: n.a.
            name: username
            protocol: openid-connect
            protocolMapper: oidc-usermodel-property-mapper

parameters:
  - description: URL of OpenShift OAuth server, with leading protocol and without trailing slash
    name: OAUTH_URL
    required: true
  - description: The namespace to deploy into
    name: NAMESPACE
    value: redhat-rhmi-rhsso
  - description: Realm name
    name: REALM
    value: testing-idp
  - description: Realm display name
    name: REALM_DISPLAY_NAME
    value: Testing IDP
  - description: IDP client client
    name: CLIENT_SECRET
    generate: expression
    from: "[a-zA-Z0-9]{12}"
