// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package threescale

import (
	"context"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sync"
)

var (
	lockSigsClientInterfaceMockCreate        sync.RWMutex
	lockSigsClientInterfaceMockDelete        sync.RWMutex
	lockSigsClientInterfaceMockGet           sync.RWMutex
	lockSigsClientInterfaceMockGetSigsClient sync.RWMutex
	lockSigsClientInterfaceMockList          sync.RWMutex
	lockSigsClientInterfaceMockStatus        sync.RWMutex
	lockSigsClientInterfaceMockUpdate        sync.RWMutex
)

// Ensure, that SigsClientInterfaceMock does implement SigsClientInterface.
// If this is not the case, regenerate this file with moq.
var _ SigsClientInterface = &SigsClientInterfaceMock{}

// SigsClientInterfaceMock is a mock implementation of SigsClientInterface.
//
//     func TestSomethingThatUsesSigsClientInterface(t *testing.T) {
//
//         // make and configure a mocked SigsClientInterface
//         mockedSigsClientInterface := &SigsClientInterfaceMock{
//             CreateFunc: func(ctx context.Context, obj runtime.Object) error {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(ctx context.Context, obj runtime.Object, opts ...client.DeleteOptionFunc) error {
// 	               panic("mock out the Delete method")
//             },
//             GetFunc: func(ctx context.Context, key types.NamespacedName, obj runtime.Object) error {
// 	               panic("mock out the Get method")
//             },
//             GetSigsClientFunc: func() client.Client {
// 	               panic("mock out the GetSigsClient method")
//             },
//             ListFunc: func(ctx context.Context, opts *client.ListOptions, list runtime.Object) error {
// 	               panic("mock out the List method")
//             },
//             StatusFunc: func() client.StatusWriter {
// 	               panic("mock out the Status method")
//             },
//             UpdateFunc: func(ctx context.Context, obj runtime.Object) error {
// 	               panic("mock out the Update method")
//             },
//         }
//
//         // use mockedSigsClientInterface in code that requires SigsClientInterface
//         // and then make assertions.
//
//     }
type SigsClientInterfaceMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, obj runtime.Object) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, obj runtime.Object, opts ...client.DeleteOptionFunc) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key types.NamespacedName, obj runtime.Object) error

	// GetSigsClientFunc mocks the GetSigsClient method.
	GetSigsClientFunc func() client.Client

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, opts *client.ListOptions, list runtime.Object) error

	// StatusFunc mocks the Status method.
	StatusFunc func() client.StatusWriter

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, obj runtime.Object) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj runtime.Object
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj runtime.Object
			// Opts is the opts argument value.
			Opts []client.DeleteOptionFunc
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key types.NamespacedName
			// Obj is the obj argument value.
			Obj runtime.Object
		}
		// GetSigsClient holds details about calls to the GetSigsClient method.
		GetSigsClient []struct {
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts *client.ListOptions
			// List is the list argument value.
			List runtime.Object
		}
		// Status holds details about calls to the Status method.
		Status []struct {
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Obj is the obj argument value.
			Obj runtime.Object
		}
	}
}

// Create calls CreateFunc.
func (mock *SigsClientInterfaceMock) Create(ctx context.Context, obj runtime.Object) error {
	if mock.CreateFunc == nil {
		panic("SigsClientInterfaceMock.CreateFunc: method is nil but SigsClientInterface.Create was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Obj runtime.Object
	}{
		Ctx: ctx,
		Obj: obj,
	}
	lockSigsClientInterfaceMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockSigsClientInterfaceMockCreate.Unlock()
	return mock.CreateFunc(ctx, obj)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedSigsClientInterface.CreateCalls())
func (mock *SigsClientInterfaceMock) CreateCalls() []struct {
	Ctx context.Context
	Obj runtime.Object
} {
	var calls []struct {
		Ctx context.Context
		Obj runtime.Object
	}
	lockSigsClientInterfaceMockCreate.RLock()
	calls = mock.calls.Create
	lockSigsClientInterfaceMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *SigsClientInterfaceMock) Delete(ctx context.Context, obj runtime.Object, opts ...client.DeleteOptionFunc) error {
	if mock.DeleteFunc == nil {
		panic("SigsClientInterfaceMock.DeleteFunc: method is nil but SigsClientInterface.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Obj  runtime.Object
		Opts []client.DeleteOptionFunc
	}{
		Ctx:  ctx,
		Obj:  obj,
		Opts: opts,
	}
	lockSigsClientInterfaceMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockSigsClientInterfaceMockDelete.Unlock()
	return mock.DeleteFunc(ctx, obj, opts...)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedSigsClientInterface.DeleteCalls())
func (mock *SigsClientInterfaceMock) DeleteCalls() []struct {
	Ctx  context.Context
	Obj  runtime.Object
	Opts []client.DeleteOptionFunc
} {
	var calls []struct {
		Ctx  context.Context
		Obj  runtime.Object
		Opts []client.DeleteOptionFunc
	}
	lockSigsClientInterfaceMockDelete.RLock()
	calls = mock.calls.Delete
	lockSigsClientInterfaceMockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *SigsClientInterfaceMock) Get(ctx context.Context, key types.NamespacedName, obj runtime.Object) error {
	if mock.GetFunc == nil {
		panic("SigsClientInterfaceMock.GetFunc: method is nil but SigsClientInterface.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key types.NamespacedName
		Obj runtime.Object
	}{
		Ctx: ctx,
		Key: key,
		Obj: obj,
	}
	lockSigsClientInterfaceMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockSigsClientInterfaceMockGet.Unlock()
	return mock.GetFunc(ctx, key, obj)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedSigsClientInterface.GetCalls())
func (mock *SigsClientInterfaceMock) GetCalls() []struct {
	Ctx context.Context
	Key types.NamespacedName
	Obj runtime.Object
} {
	var calls []struct {
		Ctx context.Context
		Key types.NamespacedName
		Obj runtime.Object
	}
	lockSigsClientInterfaceMockGet.RLock()
	calls = mock.calls.Get
	lockSigsClientInterfaceMockGet.RUnlock()
	return calls
}

// GetSigsClient calls GetSigsClientFunc.
func (mock *SigsClientInterfaceMock) GetSigsClient() client.Client {
	if mock.GetSigsClientFunc == nil {
		panic("SigsClientInterfaceMock.GetSigsClientFunc: method is nil but SigsClientInterface.GetSigsClient was just called")
	}
	callInfo := struct {
	}{}
	lockSigsClientInterfaceMockGetSigsClient.Lock()
	mock.calls.GetSigsClient = append(mock.calls.GetSigsClient, callInfo)
	lockSigsClientInterfaceMockGetSigsClient.Unlock()
	return mock.GetSigsClientFunc()
}

// GetSigsClientCalls gets all the calls that were made to GetSigsClient.
// Check the length with:
//     len(mockedSigsClientInterface.GetSigsClientCalls())
func (mock *SigsClientInterfaceMock) GetSigsClientCalls() []struct {
} {
	var calls []struct {
	}
	lockSigsClientInterfaceMockGetSigsClient.RLock()
	calls = mock.calls.GetSigsClient
	lockSigsClientInterfaceMockGetSigsClient.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *SigsClientInterfaceMock) List(ctx context.Context, opts *client.ListOptions, list runtime.Object) error {
	if mock.ListFunc == nil {
		panic("SigsClientInterfaceMock.ListFunc: method is nil but SigsClientInterface.List was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts *client.ListOptions
		List runtime.Object
	}{
		Ctx:  ctx,
		Opts: opts,
		List: list,
	}
	lockSigsClientInterfaceMockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	lockSigsClientInterfaceMockList.Unlock()
	return mock.ListFunc(ctx, opts, list)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedSigsClientInterface.ListCalls())
func (mock *SigsClientInterfaceMock) ListCalls() []struct {
	Ctx  context.Context
	Opts *client.ListOptions
	List runtime.Object
} {
	var calls []struct {
		Ctx  context.Context
		Opts *client.ListOptions
		List runtime.Object
	}
	lockSigsClientInterfaceMockList.RLock()
	calls = mock.calls.List
	lockSigsClientInterfaceMockList.RUnlock()
	return calls
}

// Status calls StatusFunc.
func (mock *SigsClientInterfaceMock) Status() client.StatusWriter {
	if mock.StatusFunc == nil {
		panic("SigsClientInterfaceMock.StatusFunc: method is nil but SigsClientInterface.Status was just called")
	}
	callInfo := struct {
	}{}
	lockSigsClientInterfaceMockStatus.Lock()
	mock.calls.Status = append(mock.calls.Status, callInfo)
	lockSigsClientInterfaceMockStatus.Unlock()
	return mock.StatusFunc()
}

// StatusCalls gets all the calls that were made to Status.
// Check the length with:
//     len(mockedSigsClientInterface.StatusCalls())
func (mock *SigsClientInterfaceMock) StatusCalls() []struct {
} {
	var calls []struct {
	}
	lockSigsClientInterfaceMockStatus.RLock()
	calls = mock.calls.Status
	lockSigsClientInterfaceMockStatus.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *SigsClientInterfaceMock) Update(ctx context.Context, obj runtime.Object) error {
	if mock.UpdateFunc == nil {
		panic("SigsClientInterfaceMock.UpdateFunc: method is nil but SigsClientInterface.Update was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Obj runtime.Object
	}{
		Ctx: ctx,
		Obj: obj,
	}
	lockSigsClientInterfaceMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockSigsClientInterfaceMockUpdate.Unlock()
	return mock.UpdateFunc(ctx, obj)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedSigsClientInterface.UpdateCalls())
func (mock *SigsClientInterfaceMock) UpdateCalls() []struct {
	Ctx context.Context
	Obj runtime.Object
} {
	var calls []struct {
		Ctx context.Context
		Obj runtime.Object
	}
	lockSigsClientInterfaceMockUpdate.RLock()
	calls = mock.calls.Update
	lockSigsClientInterfaceMockUpdate.RUnlock()
	return calls
}
