apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: cloud-resource-operator
  name: cloud-resource-operator-metrics
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      name: cloud-resource-operator
