apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: cloud-resource-operator
  name: operator-metrics-service
spec:
  ports:
  - name: http-metrics
    port: 8383
    targetPort: 8383
  selector:
    name: cloud-resource-operator
status:
  loadBalancer: {}
