// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullSecretSpec) DeepCopyInto(out *PullSecretSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullSecretSpec.
func (in *PullSecretSpec) DeepCopy() *PullSecretSpec {
	if in == nil {
		return nil
	}
	out := new(PullSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMI) DeepCopyInto(out *RHMI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMI.
func (in *RHMI) DeepCopy() *RHMI {
	if in == nil {
		return nil
	}
	out := new(RHMI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHMI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIList) DeepCopyInto(out *RHMIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RHMI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIList.
func (in *RHMIList) DeepCopy() *RHMIList {
	if in == nil {
		return nil
	}
	out := new(RHMIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHMIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIProductStatus) DeepCopyInto(out *RHMIProductStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIProductStatus.
func (in *RHMIProductStatus) DeepCopy() *RHMIProductStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIProductStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMISpec) DeepCopyInto(out *RHMISpec) {
	*out = *in
	out.PullSecret = in.PullSecret
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMISpec.
func (in *RHMISpec) DeepCopy() *RHMISpec {
	if in == nil {
		return nil
	}
	out := new(RHMISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIStageStatus) DeepCopyInto(out *RHMIStageStatus) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make(map[ProductName]*RHMIProductStatus, len(*in))
		for key, val := range *in {
			var outVal *RHMIProductStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RHMIProductStatus)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIStageStatus.
func (in *RHMIStageStatus) DeepCopy() *RHMIStageStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIStatus) DeepCopyInto(out *RHMIStatus) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make(map[StageName]*RHMIStageStatus, len(*in))
		for key, val := range *in {
			var outVal *RHMIStageStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(RHMIStageStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIStatus.
func (in *RHMIStatus) DeepCopy() *RHMIStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIStatus)
	in.DeepCopyInto(out)
	return out
}
