apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: marin3r
    control-plane: controller-manager
  name: marin3r-controller-manager-metrics-service
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager
status:
  loadBalancer: {}
