apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressspaceschemas.enmasse.io
  labels:
    app: enmasse
spec:
  group: enmasse.io
  version: v1beta1
  scope: Cluster
  names:
    kind: AddressSpaceSchema
    listKind: AddressSpaceSchemaList
    singular: addressspaceschema
    plural: addressspaceschemas
  versions:
    - name: v1beta1
      served: true
      storage: true
