//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIManagementTenant) DeepCopyInto(out *APIManagementTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIManagementTenant.
func (in *APIManagementTenant) DeepCopy() *APIManagementTenant {
	if in == nil {
		return nil
	}
	out := new(APIManagementTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIManagementTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIManagementTenantList) DeepCopyInto(out *APIManagementTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]APIManagementTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIManagementTenantList.
func (in *APIManagementTenantList) DeepCopy() *APIManagementTenantList {
	if in == nil {
		return nil
	}
	out := new(APIManagementTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *APIManagementTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIManagementTenantSpec) DeepCopyInto(out *APIManagementTenantSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIManagementTenantSpec.
func (in *APIManagementTenantSpec) DeepCopy() *APIManagementTenantSpec {
	if in == nil {
		return nil
	}
	out := new(APIManagementTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIManagementTenantStatus) DeepCopyInto(out *APIManagementTenantStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIManagementTenantStatus.
func (in *APIManagementTenantStatus) DeepCopy() *APIManagementTenantStatus {
	if in == nil {
		return nil
	}
	out := new(APIManagementTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertingEmailAddresses) DeepCopyInto(out *AlertingEmailAddresses) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertingEmailAddresses.
func (in *AlertingEmailAddresses) DeepCopy() *AlertingEmailAddresses {
	if in == nil {
		return nil
	}
	out := new(AlertingEmailAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxTarget) DeepCopyInto(out *BlackboxTarget) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxTarget.
func (in *BlackboxTarget) DeepCopy() *BlackboxTarget {
	if in == nil {
		return nil
	}
	out := new(BlackboxTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxTarget) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxTargetList) DeepCopyInto(out *BlackboxTargetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BlackboxTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxTargetList.
func (in *BlackboxTargetList) DeepCopy() *BlackboxTargetList {
	if in == nil {
		return nil
	}
	out := new(BlackboxTargetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BlackboxTargetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxTargetSpec) DeepCopyInto(out *BlackboxTargetSpec) {
	*out = *in
	if in.BlackboxTargets != nil {
		in, out := &in.BlackboxTargets, &out.BlackboxTargets
		*out = make([]BlackboxtargetData, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxTargetSpec.
func (in *BlackboxTargetSpec) DeepCopy() *BlackboxTargetSpec {
	if in == nil {
		return nil
	}
	out := new(BlackboxTargetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxTargetStatus) DeepCopyInto(out *BlackboxTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxTargetStatus.
func (in *BlackboxTargetStatus) DeepCopy() *BlackboxTargetStatus {
	if in == nil {
		return nil
	}
	out := new(BlackboxTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackboxtargetData) DeepCopyInto(out *BlackboxtargetData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackboxtargetData.
func (in *BlackboxtargetData) DeepCopy() *BlackboxtargetData {
	if in == nil {
		return nil
	}
	out := new(BlackboxtargetData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomDomainStatus) DeepCopyInto(out *CustomDomainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomDomainStatus.
func (in *CustomDomainStatus) DeepCopy() *CustomDomainStatus {
	if in == nil {
		return nil
	}
	out := new(CustomDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomSmtpStatus) DeepCopyInto(out *CustomSmtpStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomSmtpStatus.
func (in *CustomSmtpStatus) DeepCopy() *CustomSmtpStatus {
	if in == nil {
		return nil
	}
	out := new(CustomSmtpStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullSecretSpec) DeepCopyInto(out *PullSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullSecretSpec.
func (in *PullSecretSpec) DeepCopy() *PullSecretSpec {
	if in == nil {
		return nil
	}
	out := new(PullSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMI) DeepCopyInto(out *RHMI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMI.
func (in *RHMI) DeepCopy() *RHMI {
	if in == nil {
		return nil
	}
	out := new(RHMI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHMI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIList) DeepCopyInto(out *RHMIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RHMI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIList.
func (in *RHMIList) DeepCopy() *RHMIList {
	if in == nil {
		return nil
	}
	out := new(RHMIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RHMIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIProductStatus) DeepCopyInto(out *RHMIProductStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIProductStatus.
func (in *RHMIProductStatus) DeepCopy() *RHMIProductStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIProductStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMISpec) DeepCopyInto(out *RHMISpec) {
	*out = *in
	out.PullSecret = in.PullSecret
	out.AlertingEmailAddresses = in.AlertingEmailAddresses
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMISpec.
func (in *RHMISpec) DeepCopy() *RHMISpec {
	if in == nil {
		return nil
	}
	out := new(RHMISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIStageStatus) DeepCopyInto(out *RHMIStageStatus) {
	*out = *in
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make(map[ProductName]RHMIProductStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIStageStatus.
func (in *RHMIStageStatus) DeepCopy() *RHMIStageStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIStageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RHMIStatus) DeepCopyInto(out *RHMIStatus) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make(map[StageName]RHMIStageStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.CustomSmtp != nil {
		in, out := &in.CustomSmtp, &out.CustomSmtp
		*out = new(CustomSmtpStatus)
		**out = **in
	}
	if in.CustomDomain != nil {
		in, out := &in.CustomDomain, &out.CustomDomain
		*out = new(CustomDomainStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RHMIStatus.
func (in *RHMIStatus) DeepCopy() *RHMIStatus {
	if in == nil {
		return nil
	}
	out := new(RHMIStatus)
	in.DeepCopyInto(out)
	return out
}
