apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rhmis.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: RHMI
    listKind: RHMIList
    plural: rhmis
    singular: rhmi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RHMI is the Schema for the RHMI API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RHMISpec defines the desired state of Installation
          properties:
            alertingEmailAddress:
              type: string
            deadMansSnitchSecret:
              description: "DeadMansSnitchSecret is the name of a secret in the installation
                namespace containing connection details for Dead Mans Snitch. The
                secret must contain the following fields: \n url"
              type: string
            masterURL:
              type: string
            namespacePrefix:
              type: string
            operatorsInProductNamespace:
              description: OperatorsInProductNamespace is a flag that decides if the
                product operators should be installed in the product namespace (when
                set to true) or in standalone namespace (when set to false, default).
                Standalone namespace will be used only for those operators that support
                it.
              type: boolean
            pagerDutySecret:
              description: "PagerDutySecret is the name of a secret in the installation
                namespace containing PagerDuty account details. The secret must contain
                the following fields: \n serviceKey"
              type: string
            pullSecret:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              required:
              - name
              - namespace
              type: object
            routingSubdomain:
              type: string
            selfSignedCerts:
              type: boolean
            smtpSecret:
              description: "SMTPSecret is the name of a secret in the installation
                namespace containing SMTP connection details. The secret must contain
                the following fields: \n host port tls username password"
              type: string
            type:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            useClusterStorage:
              type: string
          required:
          - namespacePrefix
          - type
          type: object
        status:
          description: RHMIStatus defines the observed state of Installation
          properties:
            gitHubOAuthEnabled:
              type: boolean
            lastError:
              type: string
            preflightMessage:
              type: string
            preflightStatus:
              type: string
            smtpEnabled:
              type: boolean
            stage:
              type: string
            stages:
              additionalProperties:
                properties:
                  name:
                    type: string
                  phase:
                    type: string
                  products:
                    additionalProperties:
                      properties:
                        host:
                          type: string
                        mobile:
                          type: boolean
                        name:
                          type: string
                        operator:
                          type: string
                        status:
                          type: string
                        type:
                          type: string
                        version:
                          type: string
                      required:
                      - host
                      - name
                      - status
                      - version
                      type: object
                    type: object
                required:
                - name
                - phase
                type: object
              description: 'INSERT ADDITIONAL STATUS FIELDS - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: object
            toVersion:
              type: string
            version:
              type: string
          required:
          - lastError
          - stage
          - stages
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
